hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
title: 'Indieweb Hover Secret Message'
landing: true
steps:
  - title: 'Add the secret message'
  - title: 'Add the page background'
  - title: 'Style the box'
    completion:
      - 'engaged'
  - title: 'Hide the message'
    completion:
      - 'internal'
  - title: 'Reveal it on hover'
    completion:
      - 'external'
